### ISSUE TITLE
[FEAT] start/stop the Contact Supplier process: change the display of the main process

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#33]
**Note**: start occurs when clicking on the button of the popover of the main process

```[tasklist]
### Tasks
- [x] on start, remove the orange fill color + the moving shadow shape behing
- [x] on start, add fill color like we do for the running task of the sub-process
- [x] on start, remove the popover of the main process. It shouldn't show when mouseover the sub-process element
- [x] on stop, restore the orange fill color + moving shadow
```
