### ISSUE TITLE
[REFACTOR] Extract utils/shared code for generalization outside of this demo

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#36]
See also #120

```[tasklist]
### Extraction Tasks
- [x] `BpmnElementsSearcher`: workaround for https://github.com/process-analytics/bpmn-visualization-js/issues/2453. See https://github.com/process-analytics/bv-experimental-add-ons/issues/2
- [x] `PathResolver`: experimental implementation for https://github.com/process-analytics/bpmn-visualization-js/issues/930 and https://github.com/process-analytics/bpmn-visualization-js/issues/2402. See also https://github.com/process-analytics/bpmn-visualization-examples/pull/468. See https://github.com/process-analytics/bv-experimental-add-ons/issues/1
- [x] `BpmnElementsIdentifier`: shared utility class, that extends `ShapeUtil`. https://github.com/process-analytics/bv-experimental-add-ons/issues/31
```

```[tasklist]
### Use new shared implementation in this repository
- [x] `BpmnElementsSearcher` #121 
- [x] `PathResolver` #121
- [x] `BpmnElementsIdentifier` #121
```

**Comment by tbouffard** [comment]
All tasks are completed, so closing this issue.
