### ISSUE TITLE
[FEAT] Advertise section: improve the design

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#38]
```[tasklist]
### Tasks
- [ ] review the L&F of the close button
- [ ] the footer that displays the link to the website should have the same design as in the "diagram view" section
- [ ] moving from the advertise to the "diagram view" section (and the opposite) should be consistent
- [ ] ...
```
