### ISSUE TITLE
[FEAT] case-monitoring: Improve the content of the Main and Sub-process popovers

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#39]
### Main process

![01_main_process](https://user-images.githubusercontent.com/27200110/226642542-87a34fe3-b88f-4997-a16d-21e141033e33.png)

```[tasklist]
### Tasks
- [x] improve the wording of the introduction
- [x] table layout
- [x] rename "Contact Client" into "Contact Supplier" for consistency with the diagram (#40) and the code.
- [x] Allocate Resource: use "Actor" wording instead (as in the sub-process view)
``` 

### Sub-process

![02_sub_process](https://user-images.githubusercontent.com/27200110/226642547-13fd2c33-7130-4654-8f14-f164b3ed4519.png)

```[tasklist]
### Tasks for sub-process
- [x] align elements horizontally in the table
- [x] use real names instead of "resource 1", "resource 2", ....
- [x] Capitalize the first letter of names: "Pierre" instead of "pierre"
- [x] improve the wording of the introduction
- [x] display the buzy percentage of the actor instead of availalbility (they are all available, so this is not very releavant)
- [x] Use "Actor" instead of "resource"
```
