### ISSUE TITLE
[FEAT] Supplier Contact: use 3 real ChatGPT generated emails depending on the execution count

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#49]
```[tasklist]
### Tasks
- [ ] Generate 3 emails related to the "Supplier Contact" topic and store them
- [ ] Use them in a row depending on the execution count
- [ ] Start from the begining when reaching the 4th execution count and so on
```
