### ISSUE TITLE
[DOC] Provide specific information about the demo in the README

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#55]
```[tasklist]
### Tasks
- [ ] describe the use cases briefly and what they demonstrate
- [ ] explain how to use query parameters to select the use case. See #18
- [ ] tech env: vanilla TS, started from template
- [ ] disclaimer about the implementation. Do not use to start an real application. For instance, the asynchronous code is not handled correctly everywhere, there is no error management, ....
```
