### ISSUE TITLE
[FEAT] Review the general style of the demo

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#56]
While implementing this, also consider #35

```[tasklist]
### Tasks
- [x] ~popover theme (background color, border, shadow, ...)~ won't do
- [x] popover buttons #42 (#99)
- [x] case monitoring late task: remove the overlay (#100)
- [x] case monitoring late task: change fill color. Try #f9b842.  (#100)
- [x] ~case monitoring supplier contact: color, opacity and stroke width of the highlighted path~ won't do
- [x] case monitoring supplier contact: popover. Margin/Padding top/margin between textarea + between prompt and button. Margin padding with the popover border (#99)
- [x] case monitoring sub process: tasks highlight shadow-box, overlays, current running task (it is late, so use the same style as for the late sub-process element in the main process)  (#100)
- [x] case monitoring sub process: popover - add padding (#99)
```
