### ISSUE TITLE
[REFACTOR] Review the CSS style

### ISSUE THREAD

**Issue by tbouffard** [process-analytics/bonita-day-demo-2023#60]
```[tasklist]
### Tasks
- [ ] Clear extra CSS rules taken from other demos. Some CSS rules were copied https://process-analytics.github.io/icpm-demo-2022/ and the [predictions demo](https://github.com/process-analytics/bpmn-visualization-examples/blob/v0.33.0/demo/predictions/css/demo.css)
We may not have cleaned some extra elements.
- [ ] Review the class names and ensure they match the use case
- [ ] Check if we can import spectre.css directly in the code instead of in the page. Vite would manage the minification for us, and we could bundle several optional spectree file as well. 
```
